[package]
name = "raft-rs"
version = "0.1.0"
authors = ["Alec Von Arx <al.vonarx+fridge-dev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
